<div style ="background-color: #fff ; padding:10px; color: #446644; font-family:sans-serif;">


<a href="http://latc-project.eu/" style="text-decoration:none; float:right "><img src="http://latc-project.eu/sites/default/files/latc-logo.gif" style="border:0px"> </a>
    <h1>Welcome to eur-lex.publicdata.eu</h1>

    <div style="margin: 2em auto; background-color: #fafafa ; border-top:1px solid #ababab; padding:10px; ">
        
<p>The data contained in this dataset was extracted from <a href="http://api.epdb.eu/">An API for European Union legislation</a> and is provided as Linked Data here.</p>
<p>EUR-Lex provides access to documents published in the Official Journal of the European Union. It contains more than 2.8 million documents with such dating back to the year 1951. The <a href="http://eur-lex.europa.eu/en/index.htm">original website</a> provides only access to the original documents via search, whereas the extracted data also contains metadata for better filtering and querying possibilities.</p>
<p>If you want to <b>browse the data</b>, please use the links in the "navigation box" on the left side. Furthermore, it is possible to create your own <a href='http://eur-lex.publicdata.eu/queries/editor'>SPARQL queries</a> for obtaining lists of combined information.</p>
        <p>
        This dataset (<a href='http://eur-lex.publicdata.eu/'>http://eur-lex.publicdata.eu/</a>) was triplified and published by the research group <a href='http://aksw.org/'>AKSW (Agile Knowledge Engineering and Semantic Web)</a>.
        For further information about AKSW please visit our <a href='http://aksw.org/'>website</a>.
        </p>
<h3 style="margin-top: 20px">Additional Information</h3>
<ul style="margin: 0 0 20px 20px">
    <li><a href="http://eur-lex.publicdata.eu/model/select/?m=http%3A%2F%2Feur-lex.publicdata.eu%2F">Information about the dataset</a></li>
    <li><a href="http://eur-lex.publicdata.eu/sparql">SPARQL endpoint</a></li>
    <li><a href="http://eur-lex.publicdata.eu/extensions/page/page/dump.rdf.bz2">RDF/XML Dump</a></li>
    <li><a href="http://eur-lex.publicdata.eu/id/139911">Example resource</a></li>
    <li><a href="http://eur-lex.publicdata.eu/resource/export/f/rdfxml?r=http%3A%2F%2Feur-lex.publicdata.eu%2Fid%2F139911">Example resource (RDF/XML)</a></li>
</ul>

<h3>Structure and Schema</h3>
<ul style="margin: 0 0 20px 20px">
    <li>The dataset contains 3,380,835 triples.</li>
    <li>It contains <a href="http://www.w3.org/2002/07/owl#sameAs">owl:sameAs</a> links to <a href="http://lod-cloud.net/dbpedia">DBpedia</a>.</li>

</ul>
<h3>Terms of Use</h3>
<p style="margin: 0 0 40px 0">The data was extracted from the data sources stated above. Please refer also to their terms of use. You are responsible yourself to comply with those terms. The remaining dataset is available under the Public Domain Dedication and License (<a href="http://www.opendatacommons.org/licenses/pddl/">PDDL</a>).</p>

<p>Please visit the <a href='http://latc-project.eu/'>website</a> of the LATC project meanwhile.</p>

    </div>
</div>