<div style ="background-color: #fff ; padding:10px; color: #446644; font-family:sans-serif;">


<a href="http://latc-project.eu/" style="text-decoration:none; float:right "><img src="http://latc-project.eu/sites/default/files/latc-logo.gif" style="border:0px"> </a>
    <h1>Welcome to n-lex.publicdata.eu</h1>

    <div style="margin: 2em auto; background-color: #fafafa ; border-top:1px solid #ababab; padding:10px; ">

        <h3>N-LEX - A common gateway to national law (N-Lex)</h3>
        <p>
        <a href="http://eur-lex.europa.eu/n-lex/index_en.htm" >The original N-LEX</a> is a portal developed by the EU publications office and EU governments. It offers a unified search form to national legislation databases, a multilingual dictionary (EUROVOC) as well as a context-sensitive help. The project started with 4 national databases and has grown to 23 databases today.
        </p>
        <p>Besides the unified search form (which is not very useful for extraction purposes), the website also contains links to the respective national websites of the databases. All national databases offer a non-standardized access to their data, which in all cases is HTML or worse (e.g. PDF documents). Given the fact, that there are also no dumps of raw data (e.g. CSV) available, there is no unified N-LEX dataset that can be converted and published as Linked Data. Rather each countries legislation database has to be treated as an autonomous dataset. Thus we have chosen one country, namely Germany and converted this database into Linked Data via scraping. 


        <p>
        If you want to <b>browse the data</b>, please use the links in the "navigation box" on the left side. Furthermore, it is possible to create your own <a href='http://n-lex.publicdata.eu/sparql'>SPARQL queries</a> for obtaining lists of combined information.
        </p>
        <p>
        This dataset (<a href='http://n-lex.publicdata.eu/'>http://n-lex.publicdata.eu/</a>) was triplified and published by the research group <a href='http://aksw.org/'>AKSW (Agile Knowledge Engineering and Semantic Web)</a>.
        For further information about AKSW please visit our <a href='http://aksw.org/'>website</a>.
        </p>
<h3 style="margin-top: 20px">Additional Information</h3>
<ul style="margin: 0 0 20px 20px">
    <li><a href="http://n-lex.publicdata.eu/model/select/?m=http%3A%2F%2Fn-lex.publicdata.eu%2F">Information about the dataset</a></li>
    <li><a href="http://n-lex.publicdata.eu/sparql">SPARQL endpoint</a></li>
    <li><a href="http://n-lex.publicdata.eu/static/n-lex/1.0/n-lex_1.0-data.ttl.tar.bz2">Data (Turtle format)</a></li>
    <li><a href="http://n-lex.publicdata.eu/static/n-lex/1.0/n-lex_1.0-schema.owl.tar.bz2">Schema (RDF/XML format)</a></li>
    <li><a href="http://n-lex.publicdata.eu/static/n-lex/1.0/n-lex_1.0-links_dbpedia.ttl.tar.bz2">Links to DBpedia (Turtle format)</a></li>
    <li><a href="http://n-lex.publicdata.eu/germany/id/BJNR036900005">Example resource</a></li>
    <li><a href="http://n-lex.publicdata.eu/resource/export/f/rdfxml?r=http%3A%2F%2Fn-lex.publicdata.eu%2Fgermany%2Fid%2FBJNR036900005">Example resource (RDF/XML)</a></li>
</ul>

<h3>Structure and Schema</h3>
<ul style="margin: 0 0 20px 20px">
    <li>The dataset contains about 1,792,054 triples.</li>
    <li>It contains <a href="http://www.w3.org/2002/07/owl#sameAs">owl:sameAs</a> links to <a href="http://lod-cloud.net/dbpedia">DBpedia</a
>.</li>

</ul>
<h3>Terms of Use</h3>
<p style="margin: 0 0 40px 0">The data was extracted from the data sources stated above. Please refer also to their terms of use. You are responsible yourself to comply with those terms. The remaining dataset is available under the Public Domain Dedication and License (<a href="http://www.opendatacommons.org/licenses/pddl/">PDDL</a>).</p>
        <p>
        Please visit the <a href='http://latc-project.eu/'>website</a> of the LATC project meanwhile.
        </p>
    </div>
</div>