<div style ="background-color: #fff ; padding:10px; color: #446644; font-family:sans-serif;">


<a href="http://latc-project.eu/" style="text-decoration:none; float:right "><img src="http://latc-project.eu/sites/default/files/latc-logo.gif" style="border:0px"> </a>
    <h1>Welcome to prelex.publicdata.eu</h1>

    <div style="margin: 2em auto; background-color: #fafafa ; border-top:1px solid #ababab; padding:10px; ">
        <h3>PreLex - Access to European Union inter-institutional law</h3>
        <p>
        PreLex provides access to documents regarding inter-institutional law of the European Union. 
        The <a href="http://ec.europa.eu/prelex/apcnet.cfm?CL=en">original website</a> provides only access to the documents via search, 
        whereas the extracted data also contains metadata for better filtering and querying possibilities. 
        The data that was published as Linked Data in this task was not extracted from the original source, 
        but from an already existing <a href="http://api.epdb.eu/">API for European Union legislation</a>. 

        
        <p>If you want to <b>browse the data</b>, please use the links in the "navigation box" on the left side. Furthermore, it is possible to create your own <a href='http://prelex.publicdata.eu/queries/editor'>SPARQL queries</a> for obtaining lists of combined information.</p>
        <p>
        This dataset (<a href='http://prelex.publicdata.eu/'>http://prelex.publicdata.eu/</a>) was triplified and published by the research group <a href='http://aksw.org/'>AKSW (Agile Knowledge Engineering and Semantic Web)</a>.
        For further information about AKSW please visit our <a href='http://aksw.org/'>website</a>.
        </p>
<h3 style="margin-top: 20px">Additional Information</h3>
<ul style="margin: 0 0 20px 20px">
    <li><a href="http://prelex.publicdata.eu/model/select/?m=http%3A%2F%2Fprelex.publicdata.eu%2F">Information about the dataset</a></li>
    <li><a href="http://prelex.publicdata.eu/extensions/page/page/dump.rdf.bz2">RDF/XML Dump</a></li>
    <li><a href="http://prelex.publicdata.eu/sparql">SPARQL endpoint</a></li>
    <li><a href="http://prelex.publicdata.eu/r/organization/DG+Fisheries">Example resource</a></li>
    <li><a href="http://prelex.publicdata.eu/resource/export/f/rdfxml?r=http%3A%2F%2Fprelex.publicdata.eu%2Fr%2Forganization%2FDG%2BFisheries">Example resource (RDF/XML)</a></li>
</ul>

<h3>Structure and Schema</h3>
<ul style="margin: 0 0 20px 20px">
    <li>The dataset contains 1,051,352 triples.</li>
    <li>It contains <a href="http://www.w3.org/2002/07/owl#sameAs">owl:sameAs</a> links to <a href="http://lod-cloud.net/dbpedia">DBpedia</a
> as well as <a href="http://www.w3.org/2000/01/rdf-schema#seeAlso">rdfs:seeAlso</a> links to <a href="http://eur-lex.publicdata.eu/">Eur-Lex</a>.</li>

</ul>
<h3>Terms of Use</h3>
<p style="margin: 0 0 40px 0">The data was extracted from the data sources stated above. Please refer also to their terms of use. You are responsible yourself to comply with those terms. The remaining dataset is available under the Public Domain Dedication and License (<a href="http://www.opendatacommons.org/licenses/pddl/">PDDL</a>).</p>

        <p>
        Please visit the <a href='http://latc-project.eu/'>website</a> of the LATC project meanwhile.
        </p>
    </div>
</div>