<div style ="background-color: #fff ; padding:10px; color: #446644; font-family:sans-serif;">


<a href="http://latc-project.eu/" style="text-decoration:none; float:right "><img src="http://latc-project.eu/sites/default/files/latc-logo.gif" style="border:0px"> </a>
    <h1>Welcome to unodc.publicdata.eu</h1>

    <div style="margin: 2em auto; background-color: #fafafa ; border-top:1px solid #ababab; padding:10px; ">
        
        <h3>UNODC - Statistics on criminal justice</h3>

        <p>
        The United Nations office on Drugs and Crime (UNODC) provides <a href="http://www.unodc.org/unodc/en/data-and-analysis/statistics/" >statistical data on criminal justice</a> on a regular basis. 
        The data is provided as Excel sheets, which can be downloaded from the website.

        <p>
        If you want to <b>browse the data</b>, please use the links in the "navigation box" on the left side. Furthermore, it is possible to create your own <a href='http://unodc.publicdata.eu/sparql'>SPARQL queries</a> for obtaining lists of combined information.
        </p>
        <p>
        This dataset (<a href='http://unodc.publicdata.eu/'>http://unodc.publicdata.eu/</a>) was triplified and published by the research group <a href='http://aksw.org/'>AKSW (Agile Knowledge Engineering and Semantic Web)</a>.
        For further information about AKSW please visit our <a href='http://aksw.org/'>website</a>.
        </p>
<h3 style="margin-top: 20px">Additional Information</h3>
<ul style="margin: 0 0 20px 20px">
    <li><a href="http://unodc.publicdata.eu/model/select/?m=http%3A%2F%2Funodc.publicdata.eu%2F">Information about the dataset</a></li>
    <li><a href="http://unodc.publicdata.eu/static/unodc/1.0/unodc_1.0-data.ttl.tar.bz2">Data (Turtle format)</a></li>
    <li><a href="http://unodc.publicdata.eu/static/unodc/1.0/unodc_1.0-schema.owl.tar.bz2">Schema (RDF/XML format)</a></li>
    <li><a href="http://unodc.publicdata.eu/static/unodc/1.0/unodc_1.0-links.ttl.tar.bz2">Links (Turtle format)</a></li>
    <li><a href="http://unodc.publicdata.eu/sparql">SPARQL endpoint</a></li>
    <li><a href="http://unodc.publicdata.eu/r/observation/data/cts12_criminal_justice_resourcesCts12+total+police+personnelCountKenya2009">Example resource</a></li>
    <li><a href="http://unodc.publicdata.eu/resource/export/f/rdfxml?r=http%3A%2F%2Funodc.publicdata.eu%2Fr%2Fobservation%2Fdata%2Fcts12_criminal_justice_resourcesCts12%2Btotal%2Bpolice%2BpersonnelCountKenya2009">Example resource (RDF/XML)</a></li>
</ul>

<h3>Structure and Schema</h3>
<ul style="margin: 0 0 20px 20px">
    <li>The dataset contains about 230,000 triples.</li>
    <li>It contains <a href="http://www.w3.org/2002/07/owl#sameAs">owl:sameAs</a> links to <a href="http://lod-cloud.net/dbpedia">DBpedia</a
>.</li>

</ul>
<h3>Terms of Use</h3>
<p style="margin: 0 0 40px 0">The data was extracted from the data sources stated above. Please refer also to their terms of use. You are responsible yourself to comply with those terms. The remaining dataset is available under the Public Domain Dedication and License (<a href="http://www.opendatacommons.org/licenses/pddl/">PDDL</a>).</p>

        <p>
        Please visit the <a href='http://latc-project.eu/'>website</a> of the LATC project meanwhile.
        </p>
    </div>
</div>